### ISSUE TITLE
spanning header on `tbl_ae()` w/o strata

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#103]
Should `tbl_ae()` w/o strata specified have a default spanning header w/ `N = X`?

From `tbl_ae()` examples:

![image](https://user-images.githubusercontent.com/17747575/154537058-91046fec-9fed-4575-bb80-64f7ac9511e3.png)

```
# Example 1 -----------------------------------------------------------------
tbl_ae_ex1 <-
df_adverse_events %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    soc = system_organ_class,
    by = grade,
    strata = trt
  ) %>%
  modify_ae_header(all_ae_cols() ~ "**Grade {by}**")

# Example 2 -----------------------------------------------------------------
tbl_ae_ex2 <-
df_adverse_events %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    by = grade
  ) %>%
  modify_ae_header(all_ae_cols() ~ "**Grade {by}**")
```

**Comment by ddsjoberg** [comment]
I like the consistency in the output including these headers.

**Comment by shannonpileggi** [comment]
I think we are on different pages here. 

In example 1, strata is specified, and by default, `N = ` is included in the spanning header.

![image](https://user-images.githubusercontent.com/17747575/154550118-acccb562-2314-46c0-92dc-27a7671bff68.png)

In example 2, strata is not specified, and there is no spanning header by default.

![image](https://user-images.githubusercontent.com/17747575/154550245-6caee801-35e8-4748-b55d-42455ba0553c.png)

So regardless of whether or not strata is specified, should there always be a spanning header by default with `N = `?
