### ISSUE TITLE
`tbl_adverse_events()` allow for counting by either grade or attribution

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#13]
Users may want to tabulate aes by attribution instead of grade.  The example below errors out. 

- Should the `grade` argument be renamed to something more generic? Like `by`? I'm not particularly a fan of `by`, but don't have a better suggestion right now.
- Allow for general `by` that is not grade specific.

```
df_adverse_events %>%
     tbl_adverse_events(
         id = patient_id,
         adverse_event = adverse_event,
         soc = system_organ_class,
         grade = drug_attribution,
         strata = trt
     )

 Error: Names must be unique.
x These names are duplicated:
* "grade" at locations 5 and 6.
```

**Comment by ddsjoberg** [comment]
addressed in #17
