### ISSUE TITLE
document input variable types?

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#154]
In function documentation, should we specify that soc / ae can be factor or character?

**Comment by ddsjoberg** [comment]
I think technically they can be any data type, right? So maybe no need to specify?

I forgot if there is special handling for factors (e.g. does passing a factor change the order of SOC and AE?). If so, maybe we could add something about that? but maybe not needed?

**Comment by Meghansaha** [comment]
So, I'm playing around with this and trying to place different variable types in different options for `table_ae_count()` for example, the soc argument gives an error that makes me thinks the function wants specific types of variables possibly with this error: 

`Error: Error in /`soc=/` argument input. Select from ‘patient_id’, ‘trt’, ‘system_organ_class’, ‘adverse_event’, ‘grade’, ‘drug_attribution’, ‘any_complication’, ‘grade3_complication’`

This makes sense (SOCs are standardized categories right?), but should the readme for the arguments be a bit more fleshed out to let the user know beforehand, or is that extraneous considering that we'd expect people who are versed in AEs and SOCs to be using the package?

**Comment by shannonpileggi** [comment]
We'll come back to this if needed!
