### ISSUE TITLE
`tbl_adverse_events()` add argument to turn counting rule off

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#16]
Just in case it is needed, an option to count everything vs just counting max grade may be useful.

**Comment by shannonpileggi** [comment]
@ddsjoberg I'm not sure if this option would ever be used... let me know what you think.

**Comment by ddsjoberg** [comment]
I think we can pretty easily make this happen, but I think it should be in a separate function? One of the best parts of `tbl_adverse_event()` is the complete data calculations, and so many of our arguments would not apply to this type of table, eg `tbl_adverse_event(id=, id_df=, statistic=)`, and I think the extraneous args could be confusing.

I think it can be useful, and the code is pretty straightforward with much overlap in the arguments needed in `tbl_adverse_event()`. We can add another `tbl_strata()` to get the results by treatment, for example.

``` r
library(gtsummary)
library(gtreg)

df_adverse_events %>%
  tbl_strata(
    strata = system_organ_class,
    ~tbl_summary(
      data = .x,
      by = grade,
      statistic = adverse_event ~ "{n}",
      include = adverse_event
    ) %>%
      modify_header(all_stat_cols() ~ "**Grade {level}**") %>%
      remove_row_type(),
    .combine_with = "tbl_stack"
  ) %>%
  as_kable()
```

| **Group**                            | **Characteristic**            | **Grade 1** | **Grade 2** | **Grade 3** | **Grade 4** | **Grade 5** |
|:-------------------------------------|:------------------------------|:------------|:------------|:------------|:------------|:------------|
| Blood and lymphatic system disorders | Anaemia                       | 1           | 3           | 3           | 4           | 4           |
|                                      | Increased tendency to bruise  | 3           | 1           | 3           | 5           | 2           |
|                                      | Iron deficiency anaemia       | 3           | 3           | 6           | 1           | 0           |
|                                      | Thrombocytopenia              | 0           | 4           | 2           | 1           | 1           |
| Gastrointestinal disorders           | Difficult digestion           | 5           | 4           | 2           | 1           | 1           |
|                                      | Intestinal dilatation         | 0           | 2           | 5           | 4           | 0           |
|                                      | Myochosis                     | 3           | 4           | 2           | 1           | 0           |
|                                      | Non-erosive reflux disease    | 1           | 4           | 1           | 0           | 1           |
|                                      | Pancreatic enzyme abnormality | 0           | 3           | 4           | 1           | 1           |

<sup>Created on 2021-12-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
