### ISSUE TITLE
Re-export `as_hux_xlsx()`

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#172]
In addition to adding this, we should think a bit about how all the re-exported functions are documented.

Maybe we group them and document them in a single file. For example, all the `as_gt()`, `as_flex_table()` functions are in one help file that we add to the pkgdown reference page. Another file for the gtsummary modifiers?

We also re-export a bunch of selectors from dplyr and gtsummary...do they all go in a single help file? Then what to do with the boring re-exports, like the pipe?

**Comment by shannonpileggi** [comment]
I agree, let's discuss!
