### ISSUE TITLE
riskmetric score

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#198]
While I have _thoughts_ on the utility of the riskmetric score, it is used throughout the pharma industry. One part of the score is whether the pkg has vignettes.

Since we've moved vignettes to articles, we won't get credit for having them. Perhaps one solution is a single vingette that links to all the articles?

``` r
library(riskmetric)
#> Warning: unable to access index for repository http://rspm.mskcc.org/MSKREPO/latest/src/contrib:
#>   cannot open URL 'http://rspm.mskcc.org/MSKREPO/latest/src/contrib/PACKAGES'

pkg_ref("gtreg") |> 
  pkg_assess() |> 
  pkg_score() |> 
  purrr::pluck("has_vignettes")
#> [1] 1
#> attr(,"label")
#> [1] "A binary indicator of whether the package has any vignettes."
#> attr(,"class")
#> [1] "pkg_score" "numeric"
```

<sup>Created on 2022-10-02 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by shannonpileggi** [comment]
Yes, that is a good solution. And then maybe tell the pkgdown yaml explicitly not to include the vignette?

**Comment by ddsjoberg** [comment]
yeah, we can list the articles we want to link. good idea
