### ISSUE TITLE
`tbl_adverse_events()` allow users to change default sorting

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#2]
The SOC and AEs are sorted alphabetically. Should allow users to sort by frequency?

**Comment by shannonpileggi** [comment]
Possibly.  I think it can make the table easier to digest, but I also find it difficult when reproducing tables with updated data and the ordering changes. However, it is probably a desirable option.

**Comment by ddsjoberg** [comment]
@shannonpileggi 

Should the frequency sorting argument sort both SOC and AE? Just AE? Just SOC?

What should the API look like?
- [ ] `tbl_adverse_event(freq_sort = c("ae", "soc"))` where NULL is the default with no freq sorting, and the user can select sorting by ae, soc, or both.
- [ ] `tbl_adverse_event(freq_sort = TRUE)` would indicate to sort the AEs within SOC, or maybe it could indicate to sort by both AE and SOC?
- [ ] Something else?



![image](https://user-images.githubusercontent.com/26774684/147188369-db0b05c9-8071-44dd-abf6-f5acc44d3d3c.png)

**Comment by shannonpileggi** [comment]
I am leaning towards option 1.

So my understanding/expectation would be 

1. `tbl_adverse_event(freq_sort = NULL)` produces table arranged by alphabetical, or factor, ordering of `soc` and then `ae` within `soc`. 
2. `tbl_adverse_event(freq_sort = "soc")` produces table arranged by most frequent overall `soc`, and then alphabetical, or factor, ordering of `ae` within `soc`. 
3. `tbl_adverse_event(freq_sort = "ae")` produces table arranged by alphabetical, or factor, ordering of `soc`, and then `ae` within `soc` would be ordered by frequency overall. 
4. `tbl_adverse_event(freq_sort = c("soc", "ae"))` arranges by most frequent overall `soc` and then most frequent `ae` within `soc`.

Is this what you were thinking? Where frequency is evaluated across any `by` or `strata` specified?
