### ISSUE TITLE
Using gtreg with Shiny

### ISSUE THREAD

**Issue by rshinytools** [shannonpileggi/gtreg#209]
I am implmenting the gtreg for AE table with Shiny but I keep getting below error. Could you please help with this issue ? 

Warning: Error in UseMethod: no applicable method for 'group_vars' applied to an object of class "c('tbl_ae', 'gtsummary')"

App.R server part is defined this way 
  output$table <- render_gt(
    df_adverse_events %>% 
      tbl_ae(
        id_df = df_patient_characteristics,
        id = patient_id,
        ae = adverse_event,
        soc = system_organ_class,
        by = grade,
        strata = trt
      ) %>% 
      modify_header(all_ae_cols() ~ "**Grade {by}**") %>% 
      bold_labels()
  )
  
  UI Part 
      gt_output(outputId = "table")

**Comment by ddsjoberg** [comment]
Hello @rshinytools , 

I think this short vignette will help https://www.danieldsjoberg.com/gtsummary/articles/shiny.html

You gtreg/gtsummary table, must be convert to gt....I think that may be your underlying issue.

**Comment by rshinytools** [comment]
Thank you that solved the issue. I forgot to use as_gt().
