### ISSUE TITLE
Add an argument in `tbl_adverse_events()` that allows user to specify how cells with zero count are displayed.

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#23]

**Comment by shannonpileggi** [comment]
Ah ok as in `-` or `0 (0)`?

**Comment by ddsjoberg** [comment]
> Ah ok as in `-` or `0 (0)`?

@shannonpileggi yep!

**Comment by ddsjoberg** [comment]
I think the default should be NULL, with the option of adding an em-dash. What do you think?

**Comment by shannonpileggi** [comment]
Sounds good! I know I will prefer the em-dash so I lean towards that as default, but can go either way.

**Comment by ddsjoberg** [comment]
We can make the em-dash the default for sure! whatever will be the most helpful for you :)

Before you start this one, let's chat about it. I think we should use the `.$meta_data$df_stats` to find the zero-count cells instead of the method I previously added to the function (which was not 100% robust).

**Comment by shannonpileggi** [comment]
Ok, sounds good! Thanks for the heads up!

**Comment by ddsjoberg** [comment]
This should wait until the re-factoring is complete

**Comment by shannonpileggi** [comment]
@ddsjoberg if you want to take this to get it done faster you are welcome too.  i am not sure i will have the time to get to it before next week.  otherwise feel free to leave and i'll get to it when i can!

**Comment by ddsjoberg** [comment]
Whoever has time first, let's assign ourselves to signal to the other not to get started.

**Comment by shannonpileggi** [comment]
putting this bit here so i don't lose it

```
df_adverse_events %>%
  tbl_ae(
    id = patient_id,
    ae = adverse_event,
    soc = system_organ_class,
    by = grade, strata = trt,
    header = "**Grade {level}**"
  ) %>%
  add_overall(across = 'overall-only') %>%
  gtsummary::modify_table_body(
    ~ .x %>%
      dplyr::mutate(
        dplyr::across(gtsummary::all_stat_cols(), 
                      function(col) ifelse(col == "0 (0)", "\U2014", col))
      )
  )
```
