### ISSUE TITLE
Update `.complete_ae_data()` to allow bare column name inputs?

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#24]
@ddsjoberg removed the selecting functionality (allowing the function to accept bare and quoted column names) because the function is primarily used internally, and only the user-facing function needed the flexibility to accept unquoted column names.

BUT, we have decided to export `.complete_ae_data()`, and while few users will likely need the function, unquoted argument names will have consistency throughout the package. The only downside is the additional computational overhead to pass the arguments through the selecting functions.

**Comment by shannonpileggi** [comment]
I am ok with de-prioritizing this and seeing if it becomes needed.
