### ISSUE TITLE
Update help files to include an image of the saved gt table.

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#27]
- [ ] Build a bare-bones pkg to run all examples in a pkg, and if the examples contain a gtsummary/gt table save the table as an image
     - In gtsummary, the function only saves objects that end in `*_ex` or `*_ex1` or `*_ex2`, etc. Should this be a requirement, or simply save all table images?
     - Put the pkg on R Universe (not going to CRAN)
 - [ ] Add a script to gtreg that will use the pkg above to save the images
 - [ ] Update function help files to display the images.

**Comment by shannonpileggi** [comment]
I have no idea how to do this, but maybe we can schedule some time for me to watch you live code this?

**Comment by ddsjoberg** [comment]
Sure! The code already was present in gtsummary, hotfun, and bstfun to do this. But I feel like copying the same code for a fourth time was excessive!

I threw this little pkg together last night https://github.com/ddsjoberg/gt.doc.images

**Comment by shannonpileggi** [comment]
Ooh that is awesome!
