### ISSUE TITLE
Feature Request: Add ability to summarize AEs by "Any Grade" and  "Grade 3+", etc

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#28]
I often include tables like the one below in my manuscripts.

It can fit in quite easily into `tbl_adverse_events()`, but needs quite a bit of customization to make it work. Perhaps best to write a small wrapper for it?

![image](https://user-images.githubusercontent.com/26774684/146689684-6021bfed-2612-477b-b034-e7123049d646.png)

**Comment by shannonpileggi** [comment]
This does look like a handy summary, but it also seems like something tricky to implement, especially if the user passes grades `1-5` with some variation of `unknown`. Maybe we could outline the expected inputs?

**Comment by shannonpileggi** [comment]
What about a wrapper function that takes an argument like `counting_values`? So if your grade was `c("unknown", 1:5)` you would specify `counting_values = as.character(3:5)`

**Comment by ddsjoberg** [comment]
I was imagining an API that looked something like this:

```r
df_adverse_events %>%
  dplyr::mutate(
    comp_any = TRUE, 
    comp_g3 = grade >= 3
  ) %>%
  tbl_ae_binary( # this is a bad name
    include = c(comp_any, comp_g3),
    ae = adverse_event,
    soc = system_organ_class,
    id = patient_id
  )
```

The variables passed would all be logical, defined by the user. Then we can avoid complicated internal logic and it'd be general because it can handle any logical variable the user may need (e.g. sometimes I need a TRUE/FALSE is the AE and dose limiting tox, which is independent of grade).

Anyway, I think this can wait until the very end of development.

**Comment by shannonpileggi** [comment]
Ok!  Love the vision, looks like awesome functionality! Agreed it can wait for later.
