### ISSUE TITLE
How to make gtsummary helper functions available?

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#30]
There are a bunch of gtsummary functions that will be helpful for formatting and styling gtreg tables. How should we make them available to the users, e.g. the `modify_*()` family, bolding/italicizing, themes.

1. Re-export the functions from gtsummary to gtreg? A downside to this approach is that any new functions will need to be explicitly added to the re-export list.
2. Load gtsummary with gtreg? This would work, but I typically don't like it when a package loads another with it. It would also attach a bunch of functions the users don't need, e.g. `tbl_cross()`, `tbl_svysummary()`. Would make the autocomplete somewhat less helpful.
3. We could also just not export any of them, and users can load gtsummary if needed.

**Comment by shannonpileggi** [comment]
I think option 3 might be best, with clear documentation on what an out of the box {gtreg} table looks like and then how to take advantage of {gtsummary} helpers for modifications.

**Comment by ddsjoberg** [comment]
I had previously added these are re-exports. We'll need to keep `inline_text()` so we can add our own method. Should I remove the others?

```r
# gtsummary --------------------------------------------------------------------
#' @importFrom gtsummary as_gt
#' @export
gtsummary::as_gt

#' @importFrom gtsummary as_flex_table
#' @export
gtsummary::as_flex_table

#' @importFrom gtsummary as_hux_table
#' @export
gtsummary::as_hux_table

#' @importFrom gtsummary as_kable
#' @export
gtsummary::as_kable

#' @importFrom gtsummary as_kable_extra
#' @export
gtsummary::as_kable_extra

#' @importFrom gtsummary inline_text
#' @export
gtsummary::inline_text
```

**Comment by shannonpileggi** [comment]
Good point, I hadn't realized that. Maybe back to option 1? I'm not sure. Seems to be <10 `modify_` functions now, but do they depend on other helper functions that need to be exported as well?

**Comment by ddsjoberg** [comment]
Dependency on other functions will work themselves out, fortunately, so we don't have to import everything.
Perhaps just these:
1. The simple `modify_*()` functions (not the ones marked Advanced Modifiers)
2. Bold/Italic functions
3. I think we can leave the themes where they are.....
4. We'll need the `add_overall()` and `inline_text()` methods
5. Shall we export the `as_gt()`, `as_tibble()`, `as_flex_table()`, etc.? I think so?

**Comment by shannonpileggi** [comment]
That all sounds good to me!

**Comment by shannonpileggi** [comment]
Does `add_n` fall in this scope or is that a separate issue?

**Comment by ddsjoberg** [comment]
OH! I think a different scope. `add_n()` is an S3 method, and we'd need to write the functions to work with gtreg functions.
