### ISSUE TITLE
Improve column header when no `by=` variable specified

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#32]
``` r
library(gtreg)

df_adverse_events %>%
  tbl_adverse_events(
    id = patient_id,
    ae = adverse_event
  ) %>%
  gtsummary::as_kable()
```

| **Adverse Event**             | **TRUE** |
|:------------------------------|:---------|
| Anaemia                       | 7 (70)   |
| Difficult digestion           | 8 (80)   |
| Increased tendency to bruise  | 8 (80)   |
| Intestinal dilatation         | 6 (60)   |
| Iron deficiency anaemia       | 7 (70)   |
| Myochosis                     | 7 (70)   |
| Non-erosive reflux disease    | 6 (60)   |
| Pancreatic enzyme abnormality | 7 (70)   |
| Thrombocytopenia              | 7 (70)   |

<sup>Created on 2021-12-20 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by ddsjoberg** [comment]
Hmmm, there is an automated footnote to describe the stats...I guess I note for `"N = 50"`...but I don't have strong feelings about it.

**Comment by shannonpileggi** [comment]
K sounds like a plan!
