### ISSUE TITLE
`add_n()` option for `tbl_adverse_event`

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#38]
Per discussion in issue #30, `add_n()` option for `tbl_adverse_event` needs to be developed separately from `gtsummary::add_n()`.

**Comment by ddsjoberg** [comment]
What result do you have in mind for `tbl_adverse_event() %>% add_n()`?

**Comment by shannonpileggi** [comment]
🤦 Never mind, I don't think we need `add_n()`.
