### ISSUE TITLE
Package Planning

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#40]
@shannonpileggi do you have ideas for other functions that would live in this package?

So far it seems we have three candidate functions?
1. A function to calculate AEs with rates indicating the cohort prevalence, implemented in `tbl_adverse_event()`.
2. A function to tabulate raw AE counts (i.e. no cohort-size denominators, multiple AEs for the same patient will all be counted)
3. A function to perform the calculations described in #28

If we have a set of functions to tabulate AEs, and other functions for other types of regulatory tables (not sure what those would look like yet), it would be a good idea to have a function naming convention to group the AE summary functions together. Maybe something like `tbl_ae_*()` and we'd add a short descriptor for each type of the functions?

No need to make any decisions now; we can focus on getting the functions written. Just something to think about for making a package with cohesively named functions.

**Comment by shannonpileggi** [comment]
Thank you for this forward thinking!

A this time I do not have other candidate functions, but I'm sure more will come as I get more experience in this space.  😊 I have seen other unwieldy tables, but I am not sure yet if those are essential table or hand-me-downs of previous ways of getting the work done.

I agree - if we have a set of `ae` tables vs other tables this could be something like

1. `tbl_ae_cohort`, `tbl_ae_standard`, `tbl_ae_summarize`
2. `tbl_ae_raw`, `tbl_ae_count`
3. `tbl_ae_compare`, ....

Not particularly loving any of this, just some ideas!

**Comment by ddsjoberg** [comment]
I love getting the ideas out there! As they say, naming things is HARD!!
