### ISSUE TITLE
`tbl_adverse_event()` add n to table header

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#41]
```
df1 <-
  tibble::tibble(
    patient_id = paste0("ID", c(1,1,2,3)),
    system_organ_class = "Blood and lymphatic system disorders",
    adverse_event = c("Anaemia", "Anaemia", "Anaemia", "Increased tendency to bruise"),
    grade = c(1, 1, 1, 2),
    trt = rep("A", 4)
  )

id_valid <-
  tibble::tibble(
    patient_id = paste0("ID", 1:5),
    trt = c(rep("A", 3),rep("B", 2))
  )

  tbl_adverse_event(
    data = df1,
    id = "patient_id",
    ae = "adverse_event",
    soc = "system_organ_class",
    by = "grade",
    strata = "trt",
    id_df = id_valid,
    by_values = as.character(c(1:5))
  )

```

currently yields

![image](https://user-images.githubusercontent.com/17747575/147285580-f9674b53-8d23-45f8-be47-1fcebbd4d2d9.png)

What do you think about updating the default output to include `N = x`, similar to `gtsummary::tbl_summary()`?

**Comment by ddsjoberg** [comment]
Are you talking about in the 2nd strata row, or in the grade row?

I think Ns in the grade row will make the table too wide and difficult to read

**Comment by shannonpileggi** [comment]
2nd strata row!

so header would be:
strata
N
by

**Comment by ddsjoberg** [comment]
at the moment, gt only allows for 2 header rows, so the Ns can't be on their own row.

We could add it pretty easily to the strata row?

**Comment by shannonpileggi** [comment]
Ah I didn't realize that.  That sounds like a good solution to me!

**Comment by ddsjoberg** [comment]
Just thinking about this....

Perhaps the `tbl_ae(header=)` argument could be updated to `tbl_ae(header_by = "**{level}**")` and we could add another argument `tbl_ae(header_strata = "**{level}**")` that could be updated like `tbl_ae(header_strata = "**{level}, N = {n}**")`.
🤔 🤔 🤔
