### ISSUE TITLE
Add a one line per patient data set 

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#43]
Add a data set to pkg that is one line per patient, so we can add example using `tbl_adverse_event(id_df=)`

**Comment by ddsjoberg** [comment]
Since there are 10 patients in the AE data now, if the single line dataset has 100, the percetnages with and without `id_df=` will be exactly 10 fold off from one another...an easy eye-ball check for us and users to see how results change when supplying the one line data set

**Comment by shannonpileggi** [comment]
Sounds good!
