### ISSUE TITLE
Add a `"gtreg"` theme 

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#64]
The gtsummary package supports themes that allow us to change the defaults of functions along with other changes. Most summary tables in the regulatory space have a different format than the default `tbl_summary()` output. For example, the summary for continuous variables the summary statistics typically span multiple rows.

Other possible updates 
- Change the default precision of the percentages in `tbl_summary()` 
- Change the default precision for p-value formatting
- gtsummary uses an internal algorithm to guess the number of sigfigs to round each number. We could update it via a theme to increase the number of digits variables are rounded to

Anyway, you the know the specs of what's required best, so we can chat about it anytime we're ready to start working on this.

``` r
library(gtsummary)

trial %>%
  select(response, age, trt) %>%
  tbl_summary(
    by = trt,
    missing = "no",
    type = all_continuous() ~ "continuous2",
    statistic = all_continuous() ~ c("{N_nonmiss}", 
                                     "{median} ({p25}, {p75})",
                                     "{mean} ({sd})",
                                     "{min} - {max}"),
    digits = all_categorical() ~ list(0, purrr::partial(style_number, scale = 100, digits = 1))
  ) %>%
  add_p(pvalue_fun = purrr::partial(style_pvalue, digits = 2)) %>%
  bold_labels() %>%
  as_kable()
```

| **Characteristic** | **Drug A**, N = 98 | **Drug B**, N = 102 | **p-value** |
|:-------------------|:-------------------|:--------------------|:------------|
| **Tumor Response** | 28 (29.5%)         | 33 (33.7%)          | 0.53        |
| **Age**            |                    |                     | 0.72        |
| N                  | 91                 | 98                  |             |
| Median (IQR)       | 46 (37, 59)        | 48 (39, 56)         |             |
| Mean (SD)          | 47 (15)            | 47 (14)             |             |
| Range              | 6 - 78             | 9 - 83              |             |

<sup>Created on 2022-01-01 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by shannonpileggi** [comment]
Just leaving here so I don't forget, found an example of this implementation in the [table1](https://github.com/benjaminrich/table1) package.

**Comment by ddsjoberg** [comment]
Will export an `tbl_reg_summary()` table rather than create a gtreg theme
