### ISSUE TITLE
Update factor order of `by=` variables at the end of `.complete_ae_data()` ?

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#67]
The first levels of the `by=` variable factor are for the unobserved levels. BUT this leads to confusing column names in the final tables that are print.

We could migrate the level to the end of variable to make the column names more intuitive. This would need to be the last step in the `.complete_ae_data()` function. This will likely break a lot of unit tests and they'll need to be updated with new column names.

**Comment by shannonpileggi** [comment]
You're right, this might be a better solution than explaining the methods behind the scenes to users!
