### ISSUE TITLE
Should we add a `tbl_split()` method for the AE tables

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#75]
The AE summary tables can become quite long and we may need to split them across multiple pages. We could have a gtreg method that makes it easier to split the tables at the SOC level, for example. Then tables spanning multiple pages will have all AEs in the same SOC grouped together.

WE could also improve `tbl_split()` by allowing users to select, say "show 15 lines per page", and we could pick the most appropriate splits near 15 lines. (that could go to gtsummary). Anyway, just an idea I am getting out of my head !

**Comment by shannonpileggi** [comment]
Would this be agnostic to delivery engine (pdf, html) or specific to it?

**Comment by ddsjoberg** [comment]
At the moment, `tbl_split()` is agnostic to the output format. It just takes any gtsummary table as the input, also takes a vector of variable names where you want the splits to occur, and returns a list of gtsummary tables that have been split.

**Comment by ddsjoberg** [comment]
I do eventually want to a nice print method to `tbl_split()` tables that would be informed by the output type, eg if Word, PDF, or RTF, add a page break between the tables in the list. This is an idea that has been percolating for some time, but just haven't gotten around to it....sounds like it could be helpful with the huge AE tables.

**Comment by shannonpileggi** [comment]
Yes!  I've got PDF page splits working through Latex / kableExtra, we can work on streamlining it.

**Comment by ddsjoberg** [comment]
That is great! I am prepping the next gtsummary release this week. But before I do, I"ll convert `tbl_split()` to an S3 function so we can write a proper method for the gtreg tables. 

That said, we should probably add a gtreg class to our tables, e.g. `tbl_ae() |> class() = c("tbl_ae", "gtreg", "gtsummary")`, then we can use a method like `tbl_split.gtreg()` to handle all the gtreg tables. But maybe we just define methods like `tbl_split.tbl_ae()` because gtreg may add other tables that are not the same SOC/AE structure.

**Comment by shannonpileggi** [comment]
Decided to not do this - html output does not need table splitting and kableExtra options can handle it in pdf.
