### ISSUE TITLE
Use checks on `...` arguments for S3 methods

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#83]
The recent rlang v1.0 release includes functions for checking the `...` passed in S3 methods. We should use `rlang::check_dots_empty()` in the `add_overall()` and `inline_text()` to ensure users don't misspell an argument that gets swallowed into the abyss of the triple dots.

**Comment by shannonpileggi** [comment]
> swallowed into the abyss

You are so thoughtful!
