### ISSUE TITLE
Update the `@examplesIf` 

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#84]
We added `@examplesIf` in an effort to reduce the build times. BUT, it turns out CRAN runs them anyway and didn't reduce the example run time.

- [ ] Remove the `@examplesIf`
- [ ] Replace with `\dontttest` tags
- [ ] There still could be an issue if CRAN requires at least one fully functioning examples per function ¯\\\_(ツ)\_/¯. There seems to be inconsistent enforcement of this....

**Comment by shannonpileggi** [comment]
Sounds like something I can tackle!
