### ISSUE TITLE
Allow for adding dynamic Ns using `modify_header()` and `modify_spanning_header()`

### ISSUE THREAD

**Issue by ddsjoberg** [shannonpileggi/gtreg#87]
We could add functionality allowing us to add custom headers with dynamic Ns and percentages.

- we'd need a function like `gtsummary:::.info_tibble()` to calculate the Ns and percentages for the by and stratum levels
- the sticking point will be that the `modify_header()` function is not S3, and therefore, can't handle any custom code for AE tables
    - we could add wrappers `modify_ae_header()` and `modify_ae_spanning_header()`
    - i could make `modify_header(*)` an S3 function in the next gtsummary release, and we could add a `modify_header.tbl_ae()` method.
    - I lean toward the first.

**Comment by shannonpileggi** [comment]
Ok, the first sounds good to me!

**Comment by ddsjoberg** [comment]
As discussed
1. Remove the `header_by=` and `header_strata=` arguments, as these will now be handled in the modify functions.
2. Add `id_df=` argument to `tbl_ae_count()`. Add a description indicating this is used for column headers only.
