### ISSUE TITLE
add modify header vignette

### ISSUE THREAD

**Issue by shannonpileggi** [shannonpileggi/gtreg#96]
Show how various selectors work

**Comment by ddsjoberg** [comment]
I was thinking about this a bit...we could have the code to create a big table like this one

![image](https://user-images.githubusercontent.com/26774684/153770670-243ec421-fa38-4970-a3b2-561584ef0ff9.png)

and I can ask Jeffrey to do some photoshop magic to highlight the columns selected by various calls to the `all_*_cols()` functions. He's done something similar for me in the past with these

![crayon-tbl_summary-fns](https://user-images.githubusercontent.com/26774684/153770736-66f5f67a-ff6d-4c61-8687-4581f8cba378.png)

**Comment by shannonpileggi** [comment]
oooh yes that looks awesome!

**Comment by ddsjoberg** [comment]
I asked J about this, and he no longer has access to Photoshop and Illustrator since we retired. Do you know anyone who could make a cute figure like this?

**Comment by shannonpileggi** [comment]
Add an example to tbl_ae() showing how to remove the default spanning header.
